version: '3.0'

services:
  
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ecommerce-app
    container_name: ecommerce-app
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "src/app.py"
      MONGO_URI: "mongodb://mongo:27017/ecommerce"
    ports:
      - "5000:5000"
    volumes: 
      - ./src:/app/src
    depends_on:
      - mongo
    
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./docker/mongo-seed
    links:
      - mongo